Edit of html templates to fit cs50 tests
TypeError: 'NoneType' object is not subscriptable. Bug  was caused by rendering template in way not excpected in test.